version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - unused
    - ineffassign

formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/ashita-ai/kyoyu

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
