"""Akashi Python SDK — decision tracing for AI agent coordination."""

from akashi.client import AkashiClient, AkashiSyncClient
from akashi.exceptions import (
    AuthenticationError,
    AuthorizationError,
    ConflictError,
    AkashiError,
    NotFoundError,
    RateLimitError,
    ServerError,
    TokenExpiredError,
    ValidationError,
)
from akashi.middleware import AkashiMiddleware, AkashiSyncMiddleware
from akashi.otel import trace_id_from_context
from akashi.types import (
    Agent,
    AgentEvent,
    AgentRun,
    Alternative,
    AssessOutcome,
    AssessRequest,
    AssessResponse,
    CheckResponse,
    CompleteRunRequest,
    ConflictEvalResponse,
    ConflictLabelRecord,
    CreateAgentRequest,
    CreateGrantRequest,
    CreateRunRequest,
    Decision,
    DecisionConflict,
    EventInput,
    Evidence,
    GetRunResponse,
    Grant,
    HealthResponse,
    ListConflictLabelsResponse,
    QueryFilters,
    QueryResponse,
    RevisionsResponse,
    ScorerEvalResponse,
    SearchResponse,
    SearchResult,
    SubscriptionEvent,
    TemporalQueryRequest,
    TraceAlternative,
    TraceEvidence,
    TraceRequest,
    TraceResponse,
    UpsertConflictLabelRequest,
    ValidatePairRequest,
    ValidatePairResponse,
    VerifyResponse,
)

__all__ = [
    # Clients
    "AkashiClient",
    "AkashiSyncClient",
    # Middleware
    "AkashiMiddleware",
    "AkashiSyncMiddleware",
    # Types — domain
    "Decision",
    "Alternative",
    "Evidence",
    "DecisionConflict",
    "AgentRun",
    "AgentEvent",
    "Agent",
    "Grant",
    # Types — requests
    "TraceRequest",
    "TraceAlternative",
    "TraceEvidence",
    "QueryFilters",
    "CreateRunRequest",
    "EventInput",
    "CompleteRunRequest",
    "CreateAgentRequest",
    "CreateGrantRequest",
    "TemporalQueryRequest",
    "AssessOutcome",
    "AssessRequest",
    "ValidatePairRequest",
    "UpsertConflictLabelRequest",
    # Types — responses
    "TraceResponse",
    "CheckResponse",
    "QueryResponse",
    "SearchResult",
    "SearchResponse",
    "SubscriptionEvent",
    "GetRunResponse",
    "VerifyResponse",
    "RevisionsResponse",
    "HealthResponse",
    "AssessResponse",
    "ValidatePairResponse",
    "ConflictEvalResponse",
    "ConflictLabelRecord",
    "ListConflictLabelsResponse",
    "ScorerEvalResponse",
    # OTEL helpers
    "trace_id_from_context",
    # Exceptions
    "AkashiError",
    "AuthenticationError",
    "AuthorizationError",
    "NotFoundError",
    "ValidationError",
    "ConflictError",
    "RateLimitError",
    "ServerError",
    "TokenExpiredError",
]
